# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  sentry_enabled: false
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_app_id: "pQJRTT263awXTQlhgJoR"
    here_app_code: "_DwgkM3D2yaRFAu-jmUsaw"


development:
  <<: *default
  secret_key_base: d4edb014127adde3c3ebf40661a40d4b4d5a58c5dd7b71ce742ccbd7c60f07b14b4e813076b461a8c22eaf42194b03ceac0e33a9898aa21116b5289753b63916
  omniauth:
    developer:
      enabled: true
    saml:
      enabled: true
      idp_sso_target_url:                 "https://idp.iamfas.int.belgium.be/fas/SSORedirect/metaAlias/idp"
      assertion_consumer_service_url      : https://decidim.local.osp.cat/users/auth/saml/callback
      authn_context                       : urn:be:fedict:iam:fas:enterprise:Level300
      issuer                              : https://decidim.local.osp.cat/users/auth/saml
      protocol_binding                    : urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
      authn_context_comparison            : "minimun"
      authn_force: false
      idp_slo_target_url: https://decidim.local.osp.cat/users/auth/saml/spslo
      idp_cert                            : |
        -----BEGIN CERTIFICATE-----
        MIIFdDCCA1wCCQDn4xP4v1+3IzANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJG
        UjEOMAwGA1UECAwFUGFyaXMxHTAbBgNVBAoMFE9wZW4gU291cmNlIFBvbGl0aWNz
        MSEwHwYDVQQDDBhodHRwOi8vZGNkLmxvY2FsLm9zcC5jYXQxGzAZBgkqhkiG9w0B
        CQEWDG1ha29Ab3NwLmNhdDAeFw0xODAzMjAxNzE2NDRaFw0yODAzMTkxNzE2NDRa
        MHwxCzAJBgNVBAYTAkZSMQ4wDAYDVQQIDAVQYXJpczEdMBsGA1UECgwUT3BlbiBT
        b3VyY2UgUG9saXRpY3MxITAfBgNVBAMMGGh0dHA6Ly9kY2QubG9jYWwub3NwLmNh
        dDEbMBkGCSqGSIb3DQEJARYMbWFrb0Bvc3AuY2F0MIICIjANBgkqhkiG9w0BAQEF
        AAOCAg8AMIICCgKCAgEAs2P0WIIDGGsMqmSU1ToMUELoSk43AwCz0JQwRGEYwwUQ
        f06cR1JTrZXDkN6x0E0JX5AhEKdfNQ3fsk/Swy9uK3u+5zfjFviBLiVTb2TLmflB
        lclQhJhMGDjwBFWK2bqZEcBjsD0sQx/nEdV8QhwTHfcBt7cFQ3HoZ/41UO1Raa66
        wFcNay5LK4WD7jkV0rqFZp9Eo65Q0p1oXN3PUDsh+XyaK2DhUjEAzyGkRTS5dsDN
        HD+t0QN7kRxtDqgpOsvVwy1TNcNTZU4pgOAK883Lmvg6Z104nZ5RzmZR3gDDmwk1
        tuzOipLQCrcOpQ/A423VJvpI2CmcmlJrZz5kEZdAcWHoBLRqieIlBmGzzZbDxJAy
        csUM9iOpqWgrJPvEdQdUQxhElNBUJotFpOoYzke/QdYHMVQ2TXo6FA3Zd/BIXiNr
        n+/R1jyA7m1BwINt9//fPH9QAX4hY/9LjAJhvGIVa08Ow/Wr3EYOH+SfJYRNqzs9
        bT31PRCZOD6ReZSX2aMU9TryLsj/HvZsmRHL6vEmCHWUzQsmrI/J03yAHBZbTFlz
        65W6qFe5gBSreS9RynePAcO8oW0LeF0zWUQB3FwCFwhoLE2r6Z/qS46Pf9sy1UjF
        q4pyinzAze30MpLCmui1Sn8IEGiMO4FCtRDts+x4ZH1vLEWMc2jVm8Z8Eohkcr8C
        AwEAATANBgkqhkiG9w0BAQsFAAOCAgEAfj9MWpwp4eePoAEc7cRKEYO46OL3/NZP
        Rp0a07oxrp/HTaOlD7Osir1WCXP56CCP/HIcpw4IB/nW9fr4j8TQoPtTL2UzFgdW
        8iu+VyZ9HqScUTYbL3ALAO6CORQfOnJ9/4ivTOJhcibHwe21DCgJCs6sPshJC3y0
        ZeGE/IVdPFHMdnn52B4YAaq2zBz3icWvWFu3RpEtCgLsmc24bX+SYxPhIf9kCVwN
        Rf8zvYQA4wK/oAfKGfAkzw34GfrVeVveK1UZTrsWDd9sf3XnQ/SdyDRDOy/bMpZA
        I0kkS31ZdpMmb/gyOnm2kn9mCnBMvtEyf/ybP26g0kRywUGkAEKgPaf4WrRWtGIy
        7p+AWQV/Xe01upFcpqiL4Yl2WElklU9vTBkCFo6i7HppCvP+NZcvMtyZNXZEICre
        hYK+h5jGp88IrcoKmHVJmun2w+ATAK5yPRiIjzCdKMXvWZlRS3WSHJch8F2LslBq
        wHMMjswjz6jYT+fPzQiAsVgd0m9E0HA0X+I5FESY1As48ZFmgJ092+dpZ5CPdQlM
        PfhRc1MzhN8DbDTQrtda0Ofgp5BOtQ8umhbEIB/8bMJVzUS8egtywU7Yer0GtC1D
        tX1A+7ccyd3JEgFQbEUmbgr8LRzT/cND0EziGMsfzVlwKMkDn0Na4d3CDuOQHMyT
        qwp553T/h1I=
        -----END CERTIFICATE-----
test:
  <<: *default
  secret_key_base: 0ef0e28c0a56986b464570d6f5bc405ddea78b2c644ebef542326b54f48b572013f64abd1afe3e4f0b85dc03fa58911c3c6d1148f77513230f47df6fea41329c
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["SMTP_USERNAME"] || ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] || "heroku.com" %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  sentry_enabled: true
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  omniauth:
    developer:
      enabled: true
    saml:
      enabled: <%= ENV["OMNIAUTH_SAML_ENABLED"] %>
      idp_cert_fingerprint: <%= ENV["OMNIAUTH_IDP_CERT_FINGERPRINT"] %>
      idp_sso_target_url: <%= ENV["OMNIAUTH_SAML_IDP_SSO_TARGET_URL"] %>

