# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_api_key: "DZUvre-7RwpBIgJ3buUIJgBw2_4oK51Rvqy1HuJY7so"
  sentry:
    enabled: false
    dsn: https://29e8c3f278214fe28f82102f4bb8df86:52a8fec36107418db1175e016a1906b7@sentry.io/1316909
    js_version: "4.6.4"
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"

development:
  <<: *default
  secret_key_base: d4edb014127adde3c3ebf40661a40d4b4d5a58c5dd7b71ce742ccbd7c60f07b14b4e813076b461a8c22eaf42194b03ceac0e33a9898aa21116b5289753b63916
  omniauth:
    developer:
      enabled: true

test:
  <<: *default
  secret_key_base: 0ef0e28c0a56986b464570d6f5bc405ddea78b2c644ebef542326b54f48b572013f64abd1afe3e4f0b85dc03fa58911c3c6d1148f77513230f47df6fea41329c
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: "174ed821371b7e5eedabdf5c0e88127cf8a5ad36741e5a7b0e117b23890e34fd3b7c977e67ce88b977b1e1d7ecb3197de9d18c7b70d6116a498d785a4dd48992"
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
#  smtp_username: "d26d4e132da44be5ccce7918e0672647"
#  smtp_password: "b71767753f74d963e77a78b8f0606e0a"
#  smtp_address: "in-v3.mailjet.com"
#  smtp_domain: "opensourcepolitics.eu"
#  smtp_port: 587
#  smtp_starttls_auto: true
#  smtp_authentication: "plain"
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
